### ISSUE TITLE
Error when calling isAccountExisting for non onboarded account

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/kin-sdk-node#30]
Calling `client.isAccountExisting` with an address that does not exist on the blockchain is returning an error instead of `false`.

The error returned is:

`    {
      Error: Resourcesnotfound,
      errorcode: 404atFunction.translateHorizonError(C: \Users\willi\OneDrive\Documents\kin-    node-server\node_modules\@kinecosystem\kin-sdk-node\scripts\bin\errors.js: 241: 20)atFunction.translate(C: \Users\willi\OneDrive\Documents\kin-node-server\node_modules\@kinecosystem\kin-sdk-node\scripts\bin\errors.js: 171: 33)atAccountDataRetriever.<anonymous>(C: \Users\willi\OneDrive\Documents\kin-node-server\node_modules\@kinecosystem\kin-sdk-node\scripts\bin\blockchain\accountDataRetriever.js: 44: 45)atGenerator.throw(<anonymous>)atrejected(C: \Users\willi\OneDrive\Documents\kin-node-server\node_modules\@kinecosystem\kin-sdk-node\scripts\bin\blockchain\accountDataRetriever.js: 5: 65)atprocessTicksAndRejections(internal/process/next_tick.js: 81: 5)msg: 'Resources not found',
  errorBody: {
    type: 'https://stellar.org/horizon-errors/not_found',
    title: 'Resource Missing',
    status: 404,
    detail: 'The resource at the url requested was not found.  This is usually occurs for one of two reasons:  The url requested is not valid, or no data in our database could be found with the parameters provided.'
  },
  title: undefined,
  type: 'ResourceNotFoundError',
  errorCode: 404,
  _resultTransactionCode: undefined,
  _resultOperationsCode: undefined
}
`

This is for the Test environment - haven't checked production.

**Comment by hitwill** [comment]
The function returns `true` without an error if the account is already onboarded

**Comment by yosriz** [comment]
@hitwill thanks for reporting, this issue has been resolved but not yet released, will be fixed in next version.

**Comment by yosriz** [comment]
solved at https://github.com/kinecosystem/kin-sdk-node/releases/tag/0.9.0
