### ISSUE TITLE
Explicitly setting fee to 0 for whitelist

### ISSUE THREAD

**Issue by hitwill** [kinecosystem/kin-sdk-node#43]
I don't know if this is relevant, but unless you explicitly set the fee to 0 before whitelisting, the service still charges you a fee. If you set it to 0 it works perfectly as expected.

(I thought the fee was an upper-bound of what the client is willing to pay)

**Comment by yosriz** [comment]
@hitwill are you sure? when transaction is whitelisted fee shouldn't be deducted, no matter what the fee on the transaction is.

**Comment by hitwill** [comment]
I will run a test and confirm

**Comment by hitwill** [comment]
@yosriz - Confirmed. I am using Unity SDK and Node.js for the server. I have not changed my server, but made my client send 2 transactions. 

- Both whitelisted by server
- [One with fee 100 set.](https://laboratory.kin.org/index.html#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6ImM0YTdjNjI4NTM4ZjE1MWUwZDU2NzUxNmY0ZWY4OWVkNGYyNDNlODE5MGE1NGUwNjg2MzE5YTQ4OWQ3ODZlZWQifQ%3D%3D&network=public)
- [One with fee 0 set.](https://laboratory.kin.org/index.html#explorer?resource=transactions&endpoint=single&values=eyJ0cmFuc2FjdGlvbiI6IjUwMzkwMzcyMGExNmVjY2QwMmFiZDg5MmEwN2IzZmQ4ZjIxZTYyYTZiZDNmNGMzODQxYTdjMjc3MTNiZWE3NzAifQ%3D%3D&network=public)

**Comment by hitwill** [comment]
Whitelist function on my server (nothing special)

`

    function whitelistTransaction(data, res) {

        var response = standardResponse();
        clientTransaction = JSON.stringify(data);
        try {
             response.text = kin.account.whitelistTransaction(clientTransaction);
        } catch (err) {
            response = errorResponse(err);
        }
        respond(res, response);
    }
`

Client code to call this (nothng special also)

`

    IEnumerator WhitelistTransaction(Transaction transaction, Action<string, string> onComplete)
    {
        var postDataObj = new WhitelistPostData(transaction);
       

        string reqUrl = baseURL + whitelistURL;

        WWWForm form = new WWWForm();
        form.AddField("envelope", postDataObj.envelope);
        form.AddField("networkId", postDataObj.network_id);
        form.AddField("network_id", postDataObj.network_id); //for forward compatibility


        var req = UnityWebRequest.Post(reqUrl, form);
        yield return req.SendWebRequest();

        if (req.isNetworkError || req.isHttpError)
        {
            LogError(req.error);
            onComplete?.Invoke(null, null);
        }
        else
        {
            onComplete(req.downloadHandler.text, transaction.Id);
        }
    }

**Comment by hitwill** [comment]
Actually I understand. The TransactionResult shows the feeCharged = 0. But then transaction itself - shows the fee paid = 100.

**Comment by yosriz** [comment]
@hitwill correct, the "feeCharged" property just saying what was the requested fee for this transaction not actually what was deducted by the blockchain.
